### ISSUE TITLE
Create tickets

### ISSUE THREAD

**Issue by ExternalReality** [ExternalReality/features#3]
**As a** feature requester, **I want** to be able to create tickets, **so that** I can request a new features.

**Comment by ExternalReality** [comment]
### Tasks
- [x] Create Basic form
- [x] Use simple Object Serializer for form
- [x] Create JSON de-serializer (Aeson) with validations rules
- [x] Use rules on form (Parsley because it is quick)
- [x] Establish link to create and update
- [ ] Test create and update scenarios
