### ISSUE TITLE
Delete Tickets

### ISSUE THREAD

**Issue by ExternalReality** [ExternalReality/features#8]
As a **ticket requester**, **I would like** to be able to delete tickets, **so that** I can remove unwanted tickets.

**Comment by ExternalReality** [comment]
This is 2 because it has to reorganize ticket priority.

**Comment by ExternalReality** [comment]
### Tasks
- [ ] Make basic bulk crud operation
- [ ] Collect all ticket where the client is the same and has lesser priority
- [ ] Delete target ticket and update all other ticket priorities in collection by one.
